# SPDX-License-Identifier: MIT
annotations:
  category: Service
  licenses: MIT
apiVersion: v2
appVersion: 1.0.0
description: This chart is used to deploy the Kani service in a Kubernetes cluster.
home: N/A
icon: https://r2.kanibot.xyz/kani.png
keywords:
  - service
  - kani
maintainers:
  - name: starci183
    url: "https://x.com/0xstacynguyen"
name: service
version: 1.0.5
dependencies:
  - name: common
    version: 2.x.x
    repository: oci://registry-1.docker.io/bitnamicharts